spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_conversion?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      test-while-idle: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: false
  hbm2ddl:
    auto: update
entitymanager:
  packagesToScan: com.wanghao.dataconversion.entity
server:
  port: 8080
  servlet:
    context-path: /DataConversion